site_name: Harry's Part IIA Notes
site_description: Notes for Part IIA Engineering at the University of Cambridge
site_author: Harry Ye

theme:
    name: material
    palette:

    # Light mode
    - media: "(prefers-color-scheme: light)"
      scheme: default
      primary: '#2960A5'
      accent: indigo
      toggle:
        icon: material/toggle-switch-off-outline
        name: Switch to dark mode

    # Dark mode
    - media: "(prefers-color-scheme: dark)"
      scheme: slate
      primary: '#2960A5'
      accent: blue
      toggle:
        icon: material/toggle-switch
        name: Switch to light mode

# Extensions
markdown_extensions:
  - footnotes
  - admonition
  - pymdownx.details
  - pymdownx.superfences
  # - attr_list
  - attr_list
  - md_in_html
  - pymdownx.blocks.caption 
  - pymdownx.arithmatex:
      generic: true
  # - pymdownx.superfences
  # - pymdownx.details
  # - pymdownx.magiclink
  - pymdownx.tasklist:
      custom_checkbox: true
  - def_list
  - pymdownx.critic
  - pymdownx.caret
  - pymdownx.keys
  - pymdownx.mark
  - pymdownx.tilde
  - pymdownx.superfences:
      custom_fences:
        - name: mermaid
          class: mermaid
          format: !!python/name:pymdownx.superfences.fence_code_format

  - toc:
      permalink: true

plugins:
  - search
  - roamlinks
  #- blog
  - rss:
      match_path: blog/posts/.* 
      date_from_meta:
        as_creation: date
      categories:
        - categories
        - tags

extra_css:
  - stylesheets/extra.css
extra_javascript:
  #- assets/scripts.js
  - javascripts/mathjax.js
  - https://polyfill.io/v3/polyfill.min.js?features=es6
  - https://cdn.jsdelivr.net/npm/mathjax@3/es5/tex-mml-chtml.js
  - https://unpkg.com/mermaid/dist/mermaid.min.js
  - https://cdnjs.cloudflare.com/ajax/libs/mathjax/2.7.0/MathJax.js?config=TeX-MML-AM_CHTML 
